"""Initial migration with Asset, Transaction, UserPreferences, AssetDailyMetric

Revision ID: 0ff4825b7d29
Revises: 
Create Date: 2026-02-01 01:13:12.658185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ff4825b7d29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_price_threshold', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_name'), 'asset', ['name'], unique=False)
    op.create_index(op.f('ix_asset_symbol'), 'asset', ['symbol'], unique=False)
    op.create_table('userpreferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assetdailymetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('bollinger_upper', sa.Float(), nullable=True),
    sa.Column('bollinger_middle', sa.Float(), nullable=True),
    sa.Column('bollinger_lower', sa.Float(), nullable=True),
    sa.Column('bollinger_bandwidth', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('volume_sma_20', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('overall_signal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assetdailymetric_asset_id'), 'assetdailymetric', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assetdailymetric_metric_date'), 'assetdailymetric', ['metric_date'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_transaction_date'), 'transaction', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_date'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_assetdailymetric_metric_date'), table_name='assetdailymetric')
    op.drop_index(op.f('ix_assetdailymetric_asset_id'), table_name='assetdailymetric')
    op.drop_table('assetdailymetric')
    op.drop_table('userpreferences')
    op.drop_index(op.f('ix_asset_symbol'), table_name='asset')
    op.drop_index(op.f('ix_asset_name'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
